version: '3.9'

services:
    tododb:
      image: mcr.microsoft.com/mssql/server
      container_name: tododb
    todo.api:
      image: ${DOCKER_REGISTERY-}todoapi
      depends_on:
          - tododb
      build:
        context: .
        dockerfile: BasicClean.Api/Dockerfile
      ports:
        - "8090:80"


