version: '3.9'

services:
    tododb:
      image: mcr.microsoft.com/mssql/server
      container_name: tododb
      ports:
          - "1433:1433"
      environment:
          SA_PASSWORD: "Asd123.."
          ACCEPT_EULA: "Y"
    todo.api:
      image: ${DOCKER_REGISTERY-}todoapi
      depends_on:
          - tododb
      build:
        context: .
        dockerfile: BasicClean.Api/Dockerfile
      ports:
        - "8090:80"


