version: '3.9'

services:
  tododb:
    ports:
         - "1433:1433"
    environment:
          SA_PASSWORD: "Asd123.."
          ACCEPT_EULA: "Y"
  todo.api:
    environment:
       - "ConnectionStrings:TodoDb=Server=tododb;Database=TodoDb;User Id=sa;Password=Asd123.."


