// <auto-generated />
using System;
using BasicClean.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasicClean.Infrastructure.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BasicClean.Core.Enitties.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffe961d6-533d-4712-98c3-08a9f834a699"),
                            Content = "orem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pharetra tristique lorem, et vehicula leo pharetra eget. Sed fringilla suscipit dapibus. Aliquam sagittis vel sem sit amet consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet orci sem. In hac habitasse platea dictumst. Proin sapien mauris, aliquet id tellus auctor, condimentum condimentum elit. Suspendisse lobortis ornare neque, sed fermentum ex accumsan ac. Fusce vel nisi ipsum. Donec vestibulum maximus nisl non fermentum. Maecenas tempus quam faucibus viverra porttitor. Curabitur ac est sit amet elit convallis posuere eu id purus. Suspendisse potenti. Proin ac est ac tellus volutpat semper. Aenean eleifend elementum ultrices.",
                            CreationDate = new DateTime(2020, 11, 20, 0, 11, 54, 27, DateTimeKind.Local).AddTicks(6799),
                            IsDeleted = false,
                            State = 1,
                            Title = "Lorem Ipsum builder"
                        },
                        new
                        {
                            Id = new Guid("34925d9e-cc94-48b2-be6f-ed327b4b5ab7"),
                            Content = "Suspendisse potenti. Vestibulum vulputate tempor est. Nam feugiat ante metus, in bibendum nibh cursus vitae. Aenean tincidunt magna aliquam ante dictum, vel ultrices nibh vulputate. Nulla in consectetur felis. Nunc tincidunt, nunc sed viverra elementum, quam dolor varius diam, id porttitor justo turpis tincidunt sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus aliquet ultricies magna, ut venenatis metus vehicula a. Quisque vel leo sit amet risus aliquet efficitur. Phasellus non ipsum lobortis, porta quam vel, laoreet lorem. Sed fringilla a ipsum sit amet cursus. Sed erat augue, hendrerit vel arcu ac, tristique viverra erat. Nulla aliquet rhoncus suscipit. Cras vitae metus luctus, efficitur nulla vulputate, venenatis neque.",
                            CreationDate = new DateTime(2020, 11, 20, 0, 11, 54, 28, DateTimeKind.Local).AddTicks(5473),
                            IsDeleted = false,
                            State = 1,
                            Title = "Suspendisse potenti."
                        },
                        new
                        {
                            Id = new Guid("7e7c4d0b-c750-470b-b22d-8c45b06b3e77"),
                            Content = "Cras nec aliquam felis. Quisque consectetur odio quam, venenatis aliquam mauris pulvinar ac. Morbi tristique molestie interdum. Vivamus elementum pretium massa, a porta orci sagittis ac. Sed quis scelerisque turpis, id porttitor urna. Suspendisse mauris quam, euismod ac mi a, dignissim maximus ligula. Vivamus arcu nisl, accumsan ac aliquet ut, interdum ut sem. Ut condimentum facilisis nisl in commodo. Nam sodales arcu id metus consectetur, semper pretium lorem ultrices. Nulla libero enim, fermentum eu tortor a, maximus feugiat nunc. Aenean rhoncus augue ut nibh laoreet, ac tempus erat suscipit. Morbi nec sem posuere, efficitur leo in, accumsan sem. Nam vitae ante sed eros accumsan lobortis. Duis tristique est nec nisi tincidunt, ut mattis sapien pulvinar.",
                            CreationDate = new DateTime(2020, 11, 20, 0, 11, 54, 28, DateTimeKind.Local).AddTicks(5506),
                            IsDeleted = false,
                            State = 1,
                            Title = "Cras nec aliquam felis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
